version: '3.8'

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: vacancies
      POSTGRES_USER: nickdom
      POSTGRES_PASSWORD: 123qwe
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://nickdom:123qwe@database:5432/vacancies
      PYTHONPATH: "/app:/app/database"
    volumes:
      - ./backend:/app
      - ./database:/app/database

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      PYTHONPATH: "/app:/app/backend:/app/database"
    volumes:
      - ./bot:/app
      - ./backend:/app/backend
      - ./database:/app/database

volumes:
  db_data:
